### ISSUE TITLE
[TODO] Implement Coke's ability usage

### ISSUE THREAD

**Issue by Chen1571** [a1an-huang/CSE380-GROUP-FINAL-PROJECT#39]
Okay. So this one might be lengthy to do but I would say these are the steps:

- [ ] Add primary function to Coke's ability (this is basically launching the coke_ability sprite image as a projectile, make sure to incorporate physics to it)
- [ ] Figure out what Sprite to use such that Coke's ability is effective (it's supposed to blind an enemy)
- [ ] Putting the enemy sprite in and add its AI such that it'll be blinded by Coke's ability for a certain time

**Comment by Chen1571** [comment]
![image](https://user-images.githubusercontent.com/55843764/231639953-16953615-9fa8-44d1-934b-a0cf0ea87ed5.png)

We can probably use this for the enemy sprite

**Comment by Chen1571** [comment]
UPDATE 4/15/23:
This is actually the enemy sprite we will be using:
![image](https://user-images.githubusercontent.com/55843764/232288094-37c2409e-0798-42b8-be1a-afb557952bae.png)

The one-eyed-robot sprite had a white background so I decided not to use that.
Right now, the coke ability launches but it does not blind the enemy. Also it is a bit buggy when shooting it to the left.

**Comment by Chen1571** [comment]
UPDATE 4/16/23: Check my last checkbox in the original post :)

**Comment by Chen1571** [comment]
UPDATE 4/17/23: Fixed bug by decrementing the time of the debuff in update() 👍
