### ISSUE TITLE
[TODO] Implement Fanta's ability usage

### ISSUE THREAD

**Issue by Chen1571** [a1an-huang/CSE380-GROUP-FINAL-PROJECT#40]
Fanta has an ability to summon a healing bubble that blocks projectiles. For now, doing the healing is sufficient.

- [ ] Using the ability should spawn a bubble
- [ ] The bubble should heal the player if it is inside it
- [ ] The bubble should block projectiles coming from outside (this can be left for later)
